### ISSUE TITLE
./mksmallicu.sh

### ISSUE THREAD

**Issue by yousofkakhki** [rdoeffinger/Dictionary#68] opened 2017-05-15 10:45 UTC
getting this error when building with android studio 
and gradle wrapper and gradle build tools latest version 
`Error:Execution failed for task ':makesmallicu'.
> A problem occurred starting process 'command './mksmallicu.sh''`

**Comment by rdoeffinger** [comment] 2017-05-15 18:58
No further information before that error?
Your computer needs to be able to run (POSIX) shell scripts and needs to have the "zip" program installed.
If you are compiling on Windows, I would imagine that might cause some issues, though it works on my computers (maybe because I have WSL - the Linux on Windows subsystem - installed?).
This step is purely optional though, the build.gradle file has a comment on how you can skip it (though I haven't tested it lately).

**Comment by rdoeffinger** [comment] 2020-04-18 09:11
Closing due to not enough info to reproduce.

**Closed by rdoeffinger** 2020-04-18 09:11 UTC
