### ISSUE TITLE
still not able to read custom location for dictionaries

### ISSUE THREAD

**Issue by ghost** [rdoeffinger/Dictionary#128] opened 2020-06-12 08:54 UTC
hi
since version 5.5.0 it is not possible to open a custom dictionary location. my files are in /storage/emulated/0/customdir
version 5.4.9 is the last version that can read that dir.
best
mykey

**Comment by rdoeffinger** [comment] 2020-06-12 16:23
Android doesn't allow access to folders in the root directory anymore.
If it works with 5.4.9 on the same device the only explanation I have is that Android has an exception for apps that declare themselves incompatible with the newest version.
I don't think you'll be able to avoid finding a different location to store them in.
Since it's not on SD card anyway, why no the app specific folder it suggests (the ones with quickdic in the name)?

**Comment by mykey2** [comment] 2020-06-16 09:02
thanks for the answer. that is a pitty since I play a lot with different systems and I like my stuff stored away conveniently. just going to use the old version then. thank you again.

**Comment by rdoeffinger** [comment] 2020-06-16 20:24
Actually I just tested on my older Android 7 device and I can use /storage/emulated/0/quickdic just fine as storage directory.
It's not entirely smooth at first (it first complains it can't write the directory, and only when returning from settings asks for permissions), but then it works, even for writing.

**Comment by rdoeffinger** [comment] 2020-06-16 20:28
Same on another, Android 9 device.
Latest app version, /storage/emulated/0/quickdic is working fine after allowing the app SD-card access.

**Comment by rdoeffinger** [comment] 2021-12-04 14:49
Also implemented storage directory selector which fixes most case, though some combination of phones, Android version and paths still seem to have issues.
Closing this one, leaving issue #144 open a little longer until I could check if I can reproduce and fix any of the issues.

**Closed by rdoeffinger** 2021-12-04 14:49 UTC
