### ISSUE TITLE
dutch and german to english dictionaries work fine (the title shouldn't be "EN-DE" though)

### ISSUE THREAD

**Issue by landry314** [rdoeffinger/Dictionary#1] opened 2015-09-02 01:29 UTC
the dutch to english (EN-NL) and german to english (EN-DE) dictionaries work fine on my phone.

the orders of the entries might be better but that is probably an issue for wiktionary??

one thing though is the title in the dictionary manager for the german to english is "EN-DE", not the names of the languages like the other ones, for example "English-Japanese" or "English-Dutch". It should be changed.

thank you so much!!! i was hoping someone would save quickdic!!!! :-)

**Comment by rdoeffinger** [comment] 2015-09-04 23:42
I think the EN-DE name happens when you have an outdated dictionary.
The proper names are only given for the files that match the dictionary list in the app I think.
The entry order probably is created by the dictionary generation.
Can you give an example of the issue with the order of the entries? Then I can have a look and see if it can be improved.

**Comment by landry314** [comment] 2015-09-05 03:39
the entries are fine. i think just one i disagreed with.

i just downloaded your EN-DE dictionary. how is that "outdated"? the name should not be "EN-DE" on the Dictionary Manager screen.

**Comment by rdoeffinger** [comment] 2015-09-05 09:49
The "outdated" was just a theory, you have had an old dictionary from before.
Unfortunately I can't reproduce the issue, it is called English-German for me.
I'll keep my eyes open in case I find the cause, but unless it happens to me as well chances are low I'll manage to fix it.

**Comment by landry314** [comment] 2015-09-05 11:24
funny. i am using quickdic 5.0.1 for android and i have never had a german-english dictionary installed before this one...

**Comment by rdoeffinger** [comment] 2015-10-11 11:58
Just a sudden suspicion: 5.0.1 might be the old app, not this one which in the app store is named "QuickDic restored"? If you end up with both installed it might be hard to know which one is which as icons and name end up the same (which I considered a "feature" but can be confusing).
The English-German dictionaries were named DE-EN in that one I believe, so it would not recognize EN-DE as being English-German...

**Comment by landry314** [comment] 2015-10-11 15:21
It would be nice to put this new app in F-Droid!

**Comment by rdoeffinger** [comment] 2015-12-06 22:54
App is in F-Droid (though it is separate, so no update information).
I'm closing on the assumption that everything will work fine with this "proper" version.

**Closed by rdoeffinger** 2015-12-06 22:54 UTC

**Comment by landry314** [comment] 2015-12-07 07:01
indeed it does. i just installed the new version and the dictionary name appears perfectly. thank you!
