### ISSUE TITLE
Switching Dictionaries Doesn't Autosearch Current Search Term

### ISSUE THREAD

**Issue by landry314** [rdoeffinger/Dictionary#120] opened 2020-04-15 19:41 UTC
I use multiple translation dictionaries and straight English dictionaries too. Many times I enter a word and then I notice it is the wrong dictionary so I then switch dictionaries and the word remains in the search field but QuickDic does not use it to search. I have to delete the last character of the word then type it again to get the app to search the word.

It would make more sense when a dictionary is changed with an active search term that it then automatically searches that term.

To reproduce:
1) Enter a word and watch it automatically search that word
2) Switch dictionaries
3) Delete last letter of the search term
4) Put that letter back

Now it autosearches.

Autosearch should autosearch immediately after dictionary switch.

This should be easy to code. Just add one line to search after dictionary switch.

**Comment by rdoeffinger** [comment] 2020-04-15 20:48
I cannot reproduce, and I am fairly sure I fixed that.
Are you sure you use the latest version? 5.5.1 preferably?
If yes, it might be an issue specific to certain versions of Android or certain devices.
Please provide more detail in that case, but if I am not able to reproduce the issue that greatly reduces the chances of a fix.

**Comment by landry314** [comment] 2020-04-16 21:27
I am using QuickDic 5.5.1 and yes, it is the same issue for me, it has not been fixed.

I am using Lineage OS 16.0 (Android 9) on a Pixel 2 (walleye).

**Comment by rdoeffinger** [comment] 2020-04-17 06:14
I have tested with Lineage OS 15.1 on LG G4 and Android 9 on a Sony XZ1 and the emulator images.
I start the app, press the x next to the search to clear the previous one, enter "test", tap the flag on the top left, then tap some other flag in the popup list.
It immediately jumps to test/testament whatever is closes in the new dictionary.
Anything you do differently that would explain why you see the issue and I don't?

**Comment by landry314** [comment] 2020-04-18 08:59
The dictionaries I am using are English and English-French, English-Spanish, English-German, and many more. When I hit the flag for English or any of its pairs it fails to search. Instead it stays at the top of the dictionary like you had not entered anything.

It is very strange it doesn't work for me but does for you.

I am wondering if more people have the reaction you have or if more people have my issue.

Maybe uninstalling the app and reinstalling it from F-Droid would fix it...

**Comment by landry314** [comment] 2020-04-18 09:07
No, I just uninstalled QuickDic and reinstalled it from F-Droid and downloaded the dictionaries again and it has the same issue... it will not autosearch the current term after dictionary switch.

QuickDic 5.5.1 (ID 106)

This is quite strange...

are there any google dependencies? I am using open gapps pico...

**Comment by rdoeffinger** [comment] 2020-04-18 09:32
I tried with the F-Droid version to be sure, but it also is fine with that.
No Google stuff is used by the app, so that should not be it.
However I wonder if it might be related to the keyboard in use.
I have "Android Keyboard (AOSP)" and SwiftKey in use currently.
The other option if you are comfortable with it would be to capture a debug level logcat, which should show a whole lot of printouts related to the search that should be auto-triggered when switching languages. Which might help me find some code to review in more detail.

**Comment by rdoeffinger** [comment] 2020-04-18 09:41
Funny, I did find a comment though:
        // Without this extra delay, the call to jumpToRow that this
        // invokes doesn't always actually have any effect.
There seems to be no extra delay though.

**Comment by rdoeffinger** [comment] 2020-04-18 09:51
Ah, I could reproduce it now, by reducing a couple of random delays in the code.

**Comment by rdoeffinger** [comment] 2020-04-18 10:19
I am not sure this issue is 100% fixable, it feels like a race condition deep in the ListView code, where if it has not entirely processed a setAdapter call it fails to set the position in the list.
But I've seen some improvements with the change, so it would be good if the new build could be tested:
[Dictionary-issue120.zip](https://github.com/rdoeffinger/Dictionary/files/4496442/Dictionary-issue120.zip)

**Comment by landry314** [comment] 2020-04-20 09:59
So, I changed keyboards to AOSP and the search now works fine in 5.5.1.

I was using AnySoftKeyboard. I had no idea searching could be related to the keyboard.

I just tried the new prerelease version above with AnySoftKeyboard and it also works! So, it looks like you fixed the problem!

**Comment by rdoeffinger** [comment] 2020-04-28 18:33
Fixed version is now in Google Play beta, F-Droid should follow after it got some testing here.
Thus closing.

**Closed by rdoeffinger** 2020-04-28 18:33 UTC
