### ISSUE TITLE
Problem searching Thai

### ISSUE THREAD

**Issue by jhodgdon-drp** [rdoeffinger/Dictionary#98] opened 2018-08-08 12:40 UTC
We are planning a trip to Thailand, so I downloaded the English-Thai dictionary in this excellent app (thank you for keeping it going!!). I also enabled Thai language as an option in the (built-in) LG Keyboard on my phone (so I can now switch between English, Spanish, and Thai keyboards as I type on the phone).

So, the bug: When I go into the Thai side of the English-Thai dictionary, I find that I can search by the transliteration of words into Roman alphabet only. For instance, if I type "see" I get some words matched, such as the transliterated "see-chom-poo". But when I switch to the Thai keyboard and type Thai characters, nothing happens in the search -- it doesn't seem to recognize that the Thai characters I have entered match any words.

I was wondering if the Thai keyboard on the phone was the problem, so I went to wikipedia.org in my browser, switched to Thai language there, and verified that I can search Wikipedia in Thai using the Thai keyboard on my phone (not that I can read any of the entries, but the search worked). I also highlighted the first few characters of some random word in an entry I was looking at, and copy/pasted that into QuickDic's search box, but again I got no search results, even when I backspaced it down to just one or two characters. And I even tried copy/pasting some Thai from a Quickdic dictionary entry, and that didn't work in the search box either.

So I think the QuickDic app is not successfully matching Thai characters to characters in the Thai/English dictionary.

I hope that wasn't too much detail... as an open-source software developer myself, I always like to have as much information as possible in bug reports. I'd be happy to test further... thanks!

**Comment by rdoeffinger** [comment] 2018-08-08 21:59
Caused by overzealous apk size optimization.
Fixed in cbd442aba18333cfacfdd6cbc3a9e69bf8c09c17

**Comment by rdoeffinger** [comment] 2018-08-08 22:07
Also released to beta channel on Play Store.

**Closed by rdoeffinger** 2018-08-08 22:07 UTC

**Comment by jhodgdon-drp** [comment] 2018-08-08 23:15
Thanks for the quick action!

**Comment by jhodgdon-drp** [comment] 2018-08-09 17:02
Just wanted to let you know that I signed up for the beta/dev version of the app, and Thai searching now works fine. Thanks again!
