### ISSUE TITLE
Problem with search in French dictionary

### ISSUE THREAD

**Issue by solstag** [rdoeffinger/Dictionary#49] opened 2016-10-25 18:04 UTC
Ni!

Thank you so much for maintaining and further developing this app.

I'm using it with the French Dictionary and I have the following problem in every version since I started using it early this year:

Steps to reproduce:

1. Open QuickDic and choose the French dictionary
2. Search for any word in the range from "réethniciserait" to "repointilla"
3. QuickDic scrolls down to the word "repointilla"

Expected:

QuickDic scrolling down to the searched word.

Hope this ain't so hard to fix. Let me know if you can't reproduce or need more input.

Cheers, ale

**Comment by rdoeffinger** [comment] 2016-10-26 05:46
The problem is due to re-pointiez, desktop Java ignores the - when sorting the words, while Android does not. Obviously how to sort French words seems to be surprisingly difficult to agree on for software developers.
I had fixed that before for "words" starting with - but didn't realize it would also happen for words containing a - in the middle.
It is easy to fix, though there is a bit of a risk in doing it without also updating all dictionaries... I guess I'll try it anyway though.

**Comment by rdoeffinger** [comment] 2016-10-27 19:04
Should be fixed in latest release.

**Closed by rdoeffinger** 2016-10-27 19:04 UTC

**Comment by solstag** [comment] 2016-10-31 14:46
Amazing, thank you!
