### ISSUE TITLE
Disabling scrolling bar

### ISSUE THREAD

**Issue by ghost** [rdoeffinger/Dictionary#130] opened 2020-08-01 16:33 UTC
Would it be possible to implement an option (in settings) to disable scrolling bar or move it to the left side?

**Comment by xxxxme** [comment] 2020-08-12 20:51
This is the same as #95.

**Comment by aevw** [comment] 2020-08-12 21:39
Yes, you're right, do you think it could be implemented in not so distant future?

**Comment by rdoeffinger** [comment] 2021-01-03 09:23
I'll close this a duplicate of #95 . That doesn't mean it won't be done, however to be honest it's really far down on my personal TODO list, especially as making it an option is a rather crappy way of solving the usability issue, having it always visible causes other issues, and I have no idea if moving it to the left is even possible (and is against UI tradition which seems not great).
I.e. problem is that it would take a good bit of effort and none of the end results seem actually good, making it bad cost/benefit to invest time in from my side.

**Closed by rdoeffinger** 2021-01-03 09:23 UTC
